@echo off
echo Creating images folder...
mkdir images 2>nul

echo Downloading 1. Samosa...
powershell -Command "Invoke-WebRequest -Uri 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Samosa_in_the_making.jpg/800px-Samosa_in_the_making.jpg' -OutFile 'images\samosa.jpg'"

echo Downloading 2. Idli...
powershell -Command "Invoke-WebRequest -Uri 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Idli_Sambar.JPG/800px-Idli_Sambar.JPG' -OutFile 'images\idli.jpg'"

echo Downloading 3. Vada Pav...
powershell -Command "Invoke-WebRequest -Uri 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Vada_Pav-Indian_street_food.jpg/800px-Vada_Pav-Indian_street_food.jpg' -OutFile 'images\vadapav.jpg'"

echo Downloading 4. Poha...
powershell -Command "Invoke-WebRequest -Uri 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Poha%%2C_a_snack_made_of_beaten_rice.jpg/800px-Poha%%2C_a_snack_made_of_beaten_rice.jpg' -OutFile 'images\poha.jpg'"

echo Downloading 5. Upma...
powershell -Command "Invoke-WebRequest -Uri 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Upma_made_from_Semolina.jpg/800px-Upma_made_from_Semolina.jpg' -OutFile 'images\upma.jpg'"

echo Downloading 6. Veg Thali...
powershell -Command "Invoke-WebRequest -Uri 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Indian_vegetarian_thali.jpg/800px-Indian_vegetarian_thali.jpg' -OutFile 'images\vegthali.jpg'"

echo Downloading 7. Chinese Thali...
powershell -Command "Invoke-WebRequest -Uri 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Hakka_noodles.jpg/800px-Hakka_noodles.jpg' -OutFile 'images\noodles.jpg'"

echo Downloading 8. Fried Rice...
powershell -Command "Invoke-WebRequest -Uri 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Restaurant_seafood_fried_rice.jpg/800px-Restaurant_seafood_fried_rice.jpg' -OutFile 'images\friedrice.jpg'"

echo Downloading 9. Dal Rice...
powershell -Command "Invoke-WebRequest -Uri 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Dal_Makhani.jpg/800px-Dal_Makhani.jpg' -OutFile 'images\dalrice.jpg'"

echo Downloading 10. Paneer Sabzi...
powershell -Command "Invoke-WebRequest -Uri 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Paneer_tikka_masala.jpg/800px-Paneer_tikka_masala.jpg' -OutFile 'images\paneer.jpg'"

echo Downloading 11. Grilled Sandwich...
powershell -Command "Invoke-WebRequest -Uri 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Grilled_cheese_sandwich.jpg/800px-Grilled_cheese_sandwich.jpg' -OutFile 'images\sandwich.jpg'"

echo Downloading 12. Maggi...
powershell -Command "Invoke-WebRequest -Uri 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Maggi_Noodles.jpg/800px-Maggi_Noodles.jpg' -OutFile 'images\maggi.jpg'"

echo Downloading 13. French Fries...
powershell -Command "Invoke-WebRequest -Uri 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/French_Fries.jpg/800px-French_Fries.jpg' -OutFile 'images\fries.jpg'"

echo Downloading 14. Sweet Lassi...
powershell -Command "Invoke-WebRequest -Uri 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Lassi_with_malai.jpg/800px-Lassi_with_malai.jpg' -OutFile 'images\lassi.jpg'"

echo Downloading 15. Masala Chaas...
powershell -Command "Invoke-WebRequest -Uri 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Chaas.jpg/800px-Chaas.jpg' -OutFile 'images\chaas.jpg'"

echo Downloading 16. Cold Coffee...
powershell -Command "Invoke-WebRequest -Uri 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Frappe_coffee_in_a_glass.jpg/800px-Frappe_coffee_in_a_glass.jpg' -OutFile 'images\coldcoffee.jpg'"

echo Downloading 17. Coca Cola...
powershell -Command "Invoke-WebRequest -Uri 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Coca-Cola_glass_bottle.jpg/800px-Coca-Cola_glass_bottle.jpg' -OutFile 'images\cocacola.jpg'"

echo Downloading 18. Water Bottle...
powershell -Command "Invoke-WebRequest -Uri 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Bottled_water.jpg/800px-Bottled_water.jpg' -OutFile 'images\water.jpg'"

echo Downloading 19. Hakka Noodles...
powershell -Command "Invoke-WebRequest -Uri 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Rocoto_spaghetti.jpg/800px-Rocoto_spaghetti.jpg' -OutFile 'images\hakkanoodles.jpg'"

echo Done downloading all images!
pause
